name: 'SwiftBuild'
author: 'SwiftActions'
description: 'Executes a build of a Swift project.'

branding:
  icon: 'terminal'
  color: 'blue'

inputs:
  verbose:
    description: "Increase verbosity to include informational output"
    required: false
    default: false

runs:
  using: 'composite'
  steps:
    - run: swift run SwiftBuild --verbose {{ $inputs.verbose }}
      shell: bash
